DROP TABLE LOCATION;

CREATE TABLE LOCATION (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FIRSTNAME VARCHAR(255) DEFAULT NULL,
    LASTNAME VARCHAR(255) DEFAULT NULL,
    USERNAME VARCHAR(255) DEFAULT NULL,
    BIRTHDAY VARCHAR(255) DEFAULT NULL,
    EMAIL VARCHAR(255) DEFAULT NULL,
    PASSWORD VARCHAR(255) DEFAULT NULL,
    PROFILEDESCRIPTION VARCHAR(255) DEFAULT NULL,
    PROFILEPICTURE VARCHAR(255) DEFAULT NULL
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence