DROP TABLE IF EXISTS LOCATION;

CREATE TABLE LOCATION (
    ID INT NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    USERNAME VARCHAR(255),
    BIRTHDAY VARCHAR(255),
    EMAIL VARCHAR(255),
    PASSWORD VARCHAR(255),
    PROFILEDESCRIPTION VARCHAR(255),
    PROFILEPICTURE VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence